Resources:
  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "taskListId"
          AttributeType: "S"
        - AttributeName: "title"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "taskListId"
          KeyType: "HASH"
        - AttributeName: "title"
          KeyType: "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Task"

