Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.kenzie.capstone.service.lambda.UpdateTaskList
      CodeUri: C:\Users\brand\kenzie\ata-capstone-project-remaibowens\ServiceLambda
      Runtime: java17
      Architectures:
        - x86_64